# Generated by Django 5.2 on 2025-05-25 22:43

import api.orders.interfaces
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default=api.orders.interfaces.OrderStatus['PAYMMENT_PENDING'], max_length=50),
        ),
    ]
