# Generated by Django 5.2 on 2025-06-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_promotion_promotioncategory_promotionproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionproduct',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='promotioncategory',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='promotionsubcategory',
            name='promotion',
        ),
        migrations.AlterUniqueTogether(
            name='promotioncategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promotioncategory',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='promotionproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promotionproduct',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='promotionsubcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promotionsubcategory',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='PromotionCategory',
        ),
        migrations.DeleteModel(
            name='PromotionProduct',
        ),
        migrations.DeleteModel(
            name='PromotionSubcategory',
        ),
    ]
