services:
  db:
    image: mysql:8.0
    container_name: integracion_plataformas_mysql_db_container
    restart: always
    environment:
      MYSQL_DATABASE: webapp_db
      MYSQL_USER: webapp_user
      MYSQL_PASSWORD: webapp_password
      MYSQL_ROOT_PASSWORD: 'root123123' # testing only
    ports:
      # Map host port 3307 to container port 3306 to avoid conflicts with other MySQL instances.
      # Adjust the host port (3307) if needed.
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    # Use the dev.env file for environment variables !!! TODO

    # Backend Service (Django)
  backend:
    build: ../backend # Path to the directory containing the Dockerfile
    container_name: integracion_plataformas_django_backend
    volumes:
      - ../backend:/app # Mount the backend directory to the container for hot reloading
    ports:
      - "8100:8000" # Map host port 8000 to container port 8100 to avoid conflicts with other services.
    env_file:
      - ../backend/dev.env # Load environment variables from .env file
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ../frontend
    container_name: integracion_plataformas_angular_frontend
    volumes:
      # Mount local frontend code into the container for hot-reloading
      # :delegated for potentially better performance on macOS/Windows
      - ./frontend:/app:delegated
      # IMPORTANT: Mount an anonymous volume for node_modules
      # This prevents the node_modules from the host (potentially wrong OS/arch)
      # from overwriting the ones installed inside the container during the build.
      - /app/node_modules
    ports:
      - "4200:4200" # Map host port 4200 to container port 4200
    restart: unless-stopped

volumes:
  db_data:
    # Define the named volume for database persistence



